spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    # 젠킨스 환경변수 추가
    url: jdbc:mysql://localhost:3306/ggbro?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username : ssafy
    password : ssafy
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop                # ddl 자동 작성 여부
#          ddl-auto: update                # ddl 자동 작성 여부
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100

  data:
    redis:
      master:
        host: localhost
        port: 6379
      slaves:
        - host: localhost
          port: 6380
        - host: localhost
          port: 6381
  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      configUrl: /v3/api-docs/swagger-config
  jwt:
    access: TestAccessKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
    refresh: TestRefreshKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
    expired-min:
      refresh-expiration: 14*60*60*1000
      access-expiration: 14*60*60*1000

#server:
#  servlet:
#    context-path: /api/v1

  sql:
    init:
      mode: always
      data-locations:
        - 'classpath:/sql/data_pet.sql'
        - 'classpath:/sql/data_quest.sql'
        - 'classpath:/sql/data_achievement.sql'
        - 'classpath:/sql/create_spatial_index.sql'
        - 'classpath:/sql/data_member.sql'
        - 'classpath:/sql/data_member_info.sql'
        - 'classpath:/sql/data_member_pet.sql'
        - 'classpath:/sql/data_member_achievement.sql'
        - 'classpath:/sql/data_plogging.sql'
        - 'classpath:/sql/data_trash.sql'
        - 'classpath:/data_notice.sql'


# AWS
aws:
  access-key-id: AKIA2UC27RTFNQDD7ICX  # 젠킨스 환경변수 추가
  secret-access-key: LQBplWSgcSQLGpItWNexqfz9RbkpghrMkN/flM9h  # 젠킨스 환경변수 추가
  region: ap-northeast-2 # 젠킨스 환경변수 추가
  s3:
    bucket: ggbro # 젠킨스 환경변수 추가

# FLASK
flask:
  server-url: https://k10c206.p.ssafy.io/predict # 젠킨스 환경변수 추가
